# Site settings
title: "Nicolas' Blog"
header-img: img/home-bg.jpg
email: nicolas@di-prima.fr
copyright_name: Nicolas DI PRIMA
description: "Nicolas' personal blog"
twitter_username: nicolasdiprima
github_username:  NicolasDP
facebook_username:  nicolas.diprima0
email_username:  nicolas@di-prima.fr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
